### ISSUE TITLE
Windows line endings cause error

### ISSUE THREAD

**Issue by MushroomMaula** [bmo-at/vscode-sosml#4]
When using Windows line endings in VSCode a error from the interpreter is returned (`There was a problem with your code: Lexing failed: Invalid token " " (\uD).`). This could be fixed by either replacing windows line ending with unix ones or using `String.prototype.trim` before passing the program to `_evaluateProgram`

**Comment by bmo-at** [comment]
Yes, but could also be fixed by setting SML files to LF file endings.
Good discovery, since I have set VSCode up to * always * use LF anyway this escaped me.
I will address it through your pull request. Good initiative!

**Comment by bmo-at** [comment]
Thanks for pitching in. Fix has been released ad of 1.3.0 and 81ff75c3a065da4e54c06a4fd6411681f7964a46
